const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.TextBox,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{Спрайт: 0},
	{Платформер: 0},
	{УничтожениеВнеМакета: 0},
	{Спрайт2: 0},
	{ТайловыйФон: 0},
	{Тач: 0},
	{Текст22222: 0},
	{Спрайт3: 0},
	{ТайловыйФон2: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Частицы: 0},
	{Частицы2: 0},
	{Спрайт8: 0},
	{ТайловыйФон3: 0},
	{Спрайт9: 0},
	{Спрайт10: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{ВводТекста: 0},
	{Спрайт14: 0},
	{Спрайт222: 0},
	{Спрайт333: 0},
	{Спрайт444: 0},
	{Спрайт111: 0},
	{Текст111: 0},
	{Текст222: 0},
	{Текст333: 0},
	{Текст444: 0},
	{Спрайт15: 0},
	{ТекстОтвет: 0},
	{Текст3: 0},
	{Спрайт17: 0},
	{Спрайт16: 0},
	{Текст21212: 0},
	{Переменная1: 0},
	{код1: 0},
	{код2: 0},
	{код3: 0},
	{код4: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Тач: class extends self.IInstance {},
	Текст22222: class extends self.ITextInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	Частицы2: class extends self.IParticlesInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт222: class extends self.ISpriteInstance {},
	Спрайт333: class extends self.ISpriteInstance {},
	Спрайт444: class extends self.ISpriteInstance {},
	Спрайт111: class extends self.ISpriteInstance {},
	Текст111: class extends self.ITextInstance {},
	Текст222: class extends self.ITextInstance {},
	Текст333: class extends self.ITextInstance {},
	Текст444: class extends self.ITextInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	ТекстОтвет: class extends self.ITextInstance {},
	Текст3: class extends self.ITextInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Текст21212: class extends self.ITextInstance {}
}